"""updating UserGroup model

Revision ID: d9c0fdd2b0a5
Revises: 41c5b1abc3da
Create Date: 2024-02-28 06:07:46.968351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c0fdd2b0a5'
down_revision = '41c5b1abc3da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=80), nullable=True))
        batch_op.drop_column('member_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_count', sa.INTEGER(), nullable=True))
        batch_op.drop_column('message')

    # ### end Alembic commands ###
